# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NewBegin
brief-intro: A new start
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ygao12.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username: ygao12
email:
weibo_username:
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer: A very new begin

duoshuo_shortname:
disqus_shortname: ygao12

baidu_tongji_id:
google_analytics_id:

# Build settings
markdown: kramdown
#redcarpet

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
