permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: redcarpet
markdown: kramdown

# 作者信息
author: 
  name: ygao12
  email: miegao12@gmail.com
  github: http://github.com/ygao12

# 站点信息
title: 新起点
description: New Begin
url: http://ygao12.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: ygao12

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - MechineLearning 
  - Python

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
